#!/usr/bin/env python3
"""Script to translate Russian comments to English in main.zig"""

import re

# Additional translations for mixed Russian/English comments
additional_translations = {
    # Mixed comments
    "// Расстояние от верхнего края (чем дальше вверх, тем быстрее)": "// Distance from top edge (further up = faster)",
    "// Расстояние от нижнего края (чем дальше вниз, тем быстрее)": "// Distance from bottom edge (further down = faster)",
    "// Горизонтальный авто-скролл с ускорением по расстоянию": "// Horizontal auto-scroll with distance acceleration",
    "// Update позицию курсора если был скролл": "// Update cursor position if scrolled",
    "// Не перестраиваем индекс - используем существующий (он валиден пока текст не менялся)": "// Don't rebuild index - use existing (valid while text unchanged)",
    "// Apply инерцию скролла": "// Apply scroll inertia",
    "// Трение": "// Friction",
    "// Handle события мыши": "// Handle mouse events",
    "// Remove фокус с редактора при любом клике": "// Remove focus from editor on any click",
    "(фокус вернётся если кликнули в область редактора)": "(focus will return if clicked in editor area)",
    "// Check resize края (8px от края)": "// Check resize edge (8px from edge)",
    "// Check край sidebar для resize (визуальный край = sidebar_width - 6)": "// Check sidebar edge for resize (visual edge = sidebar_width - 6)",
    "// Begin drag вертикального скроллбара": "// Begin vertical scrollbar drag",
    "// Begin drag горизонтального скроллбара": "// Begin horizontal scrollbar drag",
    "// Close button area (обновлено под новый дизайн)": "// Close button area (updated for new design)",
    "// Кликабельная область включает чекбокс и лейбл": "// Clickable area includes checkbox and label",
    "// Reset скорости при переключении": "// Reset velocity on toggle",
    "// Save в ~/.mncode": "// Save to ~/.mncode",
    "// Slider click - начинаем drag": "// Slider click - start drag",
    "// Количество items в каждом меню": "// Number of items in each menu",
    "// New - новая вкладка": "// New - new tab",
    "// Save текущую позицию скролла": "// Save current scroll position",
    "// Clear буфер для новой вкладки": "// Clear buffer for new tab",
    "// Create новую вкладку": "// Create new tab",
    "// Open File - открыть файл через zenity": "// Open File - open file via zenity",
    "// Нет пути - вызываем Save As": "// No path - call Save As",
    "// Delete текущую вкладку": "// Delete current tab",
    "// Load содержимое активной вкладки": "// Load active tab content",
    "// Последняя вкладка - просто очищаем": "// Last tab - just clear",
    "// Undo - пока не реализовано": "// Undo - not yet implemented",
    "// Redo - пока не реализовано": "// Redo - not yet implemented",
    "// Cut - использует системный буфер обмена": "// Cut - uses system clipboard",
    "// Copy - использует системный буфер обмена": "// Copy - uses system clipboard",
    "// Paste - использует системный буфер обмена": "// Paste - uses system clipboard",
    "// Фокус на поиск": "// Focus on search",
    "// Check кнопки окна (справа, единый блок)": "// Check window buttons (right, unified block)",
    "// Drag за остальную часть titlebar": "// Drag by rest of titlebar",
    "// Клик в sidebar": "// Click in sidebar",
    "// Check клик на sidebar tabs": "// Check click on sidebar tabs",
    "// 4 вкладки: Explorer, Search, Git, Plugins": "// 4 tabs: Explorer, Search, Git, Plugins",
    "// Клик на кнопку Open Folder (когда папка не открыта)": "// Click on Open Folder button (when folder not open)",
    "// Клик на кнопки файлового менеджера (New File, New Folder, Delete)": "// Click on file manager buttons (New File, New Folder, Delete)",
    "// Клик на файлы только если Files tab активен": "// Click on files only if Files tab is active",
    "// Клик на папку - раскрываем/сворачиваем": "// Click on folder - expand/collapse",
    "// Expand - загружаем дочерние элементы": "// Expand - load child elements",
    "// Collapse - скрываем дочерние элементы": "// Collapse - hide child elements",
    "// Клик на файл - открываем во вкладке": "// Click on file - open in tab",
    "// Check, не открыт ли уже": "// Check if already open",
    "// Switch на существующую вкладку": "// Switch to existing tab",
    "// Create новую вкладку для плагина": "// Create new tab for plugin",
    "// Имя файла": "// File name",
    "// Клик на Search tab": "// Click on Search tab",
    "// Клик на плагины (Plugins tab)": "// Click on plugins (Plugins tab)",
    "// Check, не открыта ли уже вкладка этого плагина": "// Check if this plugin tab is already open",
    "// Switch на вкладку": "// Switch to tab",
    "// Имя вкладки = имя плагина": "// Tab name = plugin name",
    "// Check клик в tab bar (координаты совпадают с render, with zoom)": "// Check click in tab bar (coordinates match render, with zoom)",
    "// Клик в tab bar": "// Click in tab bar",
    "// Check клик на кнопку закрытия": "// Check click on close button",
    "// Close вкладку": "// Close tab",
    "// Для плагин-вкладок не нужно загружать файл": "// Plugin tabs don't need to load file",
    "// Check клик на кнопку \"+\"": "// Check click on \"+\" button",
    "// Новая вкладка": "// New tab",
    "// Check клик на кнопки справа (Run, Panel)": "// Check click on right buttons (Run, Panel)",
    "// Panel button (крайняя справа)": "// Panel button (rightmost)",
    "// Run button (левее Panel)": "// Run button (left of Panel)",
    "// Get путь к файлу": "// Get file path",
    "// Search for плагин для этого файла": "// Search for plugin for this file",
    "// Get команды запуска от плагина (через запятую)": "// Get run commands from plugin (comma-separated)",
    "// Parse команды по запятой и пробуем каждую": "// Parse commands by comma and try each",
    "// Check существование команды через which": "// Check command existence via which",
    "// Команда не найдена": "// Command not found",
    "// Build полную команду": "// Build full command",
    "// Execute команду": "// Execute command",
    "// Parse вывод по строкам": "// Parse output by lines",
    "// Determine тип строки (ошибка/предупреждение)": "// Determine line type (error/warning)",
    "// Успешно выполнили": "// Successfully executed",
    "// Check клик в области bottom panel": "// Check click in bottom panel area",
    "// Клик в bottom panel": "// Click in bottom panel",
    "// Resize handle area (первые 10 пикселей)": "// Resize handle area (first 10 pixels)",
    "// Close button (справа)": "// Close button (right)",
    "// Клик вне панели - в редакторе": "// Click outside panel - in editor",
    "// Клик в редакторе": "// Click in editor",
    "// Return фокус редактору": "// Return focus to editor",
    "// Shift+клик: расширяем выделение": "// Shift+click: extend selection",
    "// Обычный клик: начинаем новое выделение": "// Normal click: start new selection",
    "// Отпускание ЛКМ": "// Left mouse button release",
    "// Если anchor == cursor, значит просто клик без движения - убираем выделение": "// If anchor == cursor, just click without movement - remove selection",
    "// Save настройки если слайдер перетаскивался": "// Save settings if slider was dragged",
    "// Handle события клавиатуры": "// Handle keyboard events",
    "// Новое нажатие - запоминаем для repeat": "// New press - remember for repeat",
    "// Отмечаем навигацию для скролла": "// Mark navigation for scroll",
    "// Handle ввод в поле поиска через общий модуль": "// Handle search field input via common module",
    "// Re-search при изменении": "// Re-search on change",
    "// Start key repeat для поиска": "// Start key repeat for search",
    "// Input в терминал если он в фокусе": "// Input to terminal if focused",
    "// Input в глобальный поиск если он в фокусе": "// Input to global search if focused",
    "// Input в редактор только если он в фокусе": "// Input to editor only if focused",
    "// Enable умное редактирование для всех языков программирования": "// Enable smart editing for all programming languages",
    "// Delete выделение если есть": "// Delete selection if exists",
    "// Get текущий отступ": "// Get current indent",
    "// Insert newline + отступ": "// Insert newline + indent",
    "// Add 4 пробела": "// Add 4 spaces",
    "// Check: если следующий символ = close_ch, просто перескакиваем": "// Check: if next char = close_ch, just skip over",
    "// Пользователь вводит кавычку, а она уже есть - перескакиваем": "// User types quote, but it already exists - skip over",
    "// Пользователь вводит закрывающую скобку, а она уже есть - перескакиваем": "// User types closing bracket, but it already exists - skip over",
    "// Insert открывающую и закрывающую скобку/кавычку": "// Insert opening and closing bracket/quote",
    "// Cursor между скобками": "// Cursor between brackets",
    "// Отпускание": "// Release",
    "// Отпускание для поиска": "// Release for search",
    "// Key repeat логика - только если редактор в фокусе": "// Key repeat logic - only if editor is focused",
    "// Check ускорение (после 8 сек) - только для навигации": "// Check acceleration (after 8 sec) - only for navigation",
    "// Repeat с интервалом": "// Repeat at interval",
    "// Key repeat для поля поиска": "// Key repeat for search field",
    "// Scroll за курсором ТОЛЬКО при навигации стрелками": "// Scroll with cursor ONLY during arrow navigation",
    "// Позиция курсора на экране (всё поле двигается вместе)": "// Cursor position on screen (entire field moves together)",
    "// Scroll вправо если курсор ушёл за правый край": "// Scroll right if cursor went past right edge",
    "// Scroll влево если курсор ушёл за левый край": "// Scroll left if cursor went past left edge",
    "// Update анимации раскрытия папок": "// Update folder expansion animations",
    "// Плавная анимация с easing": "// Smooth animation with easing",
    "// Auto-correct scroll_y при изменении контента (with zoom)": "// Auto-correct scroll_y when content changes (with zoom)",
    "// Redraw": "// Redraw",
    "// Determine тип изменений для оптимизации": "// Determine change type for optimization",
    "// Scroll требует полной перерисовки": "// Scroll requires full redraw",
    "// Check изменение выделения": "// Check selection change",
    "// Selection change требует перерисовки": "// Selection change requires redraw",
    "// Tell Wayland какие регионы изменились (damage reporting)": "// Tell Wayland which regions changed (damage reporting)",
    "// Пока делаем полный damage, позже можно оптимизировать": "// For now do full damage, can optimize later",
    "// Save состояние для следующего кадра": "// Save state for next frame",
    "// Exclude зону скроллбаров (scrollbar_size=10, margin=4)": "// Exclude scrollbar zone (scrollbar_size=10, margin=4)",
    "// If мы в зоне скроллбара - не ресайзим": "// If in scrollbar zone - don't resize",
    "// O(1) jump к нужной строке через индекс": "// O(1) jump to needed line via index",
    "// Index недоступен или строка за пределами - return end": "// Index unavailable or line out of bounds - return end",
    "// Get начало строки за O(1)": "// Get line start in O(1)",
    "// Find позицию в строке (только внутри одной строки - fast)": "// Find position in line (only within one line - fast)",
    "// Use text_cache напрямую если доступен": "// Use text_cache directly if available",
    "// Ctrl+A - select all": "// Ctrl+A - select all",
    "// Ctrl+C - copy в системный буфер обмена": "// Ctrl+C - copy to system clipboard",
    "// Ctrl+X - cut": "// Ctrl+X - cut",
    "// Ctrl+V - paste из системного буфера обмена": "// Ctrl+V - paste from system clipboard",
    "// Try paste из системного буфера обмена": "// Try to paste from system clipboard",
    "// Fallback на внутренний буфер": "// Fallback to internal buffer",
    "// Navigation keys с учётом shift": "// Navigation keys accounting for shift",
    "// If shift зажат, начинаем/расширяем выделение": "// If shift held, start/extend selection",
    "// If было выделение без shift, переходим к краю выделения": "// If there was selection without shift, go to selection edge",
    "// Perform перемещение": "// Perform movement",
    "// Backspace/Delete - delete выделение если есть": "// Backspace/Delete - delete selection if exists",
    "// Character input - replaces выделение (но не вводим при Ctrl)": "// Character input - replaces selection (but don't input with Ctrl)",
    "// Не вводим символы когда Ctrl зажат": "// Don't input characters when Ctrl is held",
    "// Move cursor к началу диапазона и delete forward": "// Move cursor to range start and delete forward",
    "/// Find все вхождения query в text_buffer и save позиции в matches": "/// Find all occurrences of query in text_buffer and save positions in matches",
    "// Skip найденное совпадение": "// Skip found match",
    "/// Find индекс ближайшего совпадения к позиции курсора": "/// Find index of nearest match to cursor position",
    "// Copy во внутренний буфер для fallback": "// Copy to internal buffer for fallback",
    "// Copy в системный буфер обмена": "// Copy to system clipboard",
    "// Find позицию в целевой строке": "// Find position in target line",
    "// Transparent background для скруглённых углов": "// Transparent background for rounded corners",
    "// Get масштабированные размеры UI элементов": "// Get scaled UI element sizes",
    "// Rounded window background": "// Rounded window background",
    "// Titlebar с меню": "// Titlebar with menu",
    "// Editor starts после titlebar и sidebar (с паддингом)": "// Editor starts after titlebar and sidebar (with padding)",
    "// Bottom panel уменьшает высоту редактора": "// Bottom panel reduces editor height",
    "// Soft shadow для editor": "// Soft shadow for editor",
    "// Rounded background текстового поля": "// Rounded text field background",
    "// Enable scissor для обрезки контента по границам редактора": "// Enable scissor to clip content to editor bounds",
    "// Check, открыта ли вкладка плагина": "// Check if plugin tab is open",
    "// === Plugin details rendering ===": "// === Plugin details rendering ===",
    "// Plugin title": "// Plugin title",
    "// Version": "// Version",
    "// Author": "// Author",
    "// Extensions": "// Extensions",
    "// Description": "// Description",
    "// Simple line wrap (каждые 80 символов)": "// Simple line wrap (every 80 characters)",
    "// Всё текстовое поле moves вместе с scroll_x": "// Entire text field moves with scroll_x",
    "// Separator между номерами строк и кодом": "// Separator between line numbers and code",
    "// === VIRTUALIZATION: Draw only visible lines + buffer ===": "// === VIRTUALIZATION: Draw only visible lines + buffer ===",
    "// Line buffer сверху и снизу": "// Line buffer above and below",
    "// Get смещение первой видимой строки - O(1) via index": "// Get first visible line offset - O(1) via index",
    "// Update global cache для совместимости": "// Update global cache for compatibility",
    "// Use cached values": "// Use cached values",
    "// Draw only visible lines": "// Draw only visible lines",
    "// Loop guard": "// Loop guard",
    "// Get line": "// Get line",
    "// Infinite loop guard - offset должно продвигаться": "// Infinite loop guard - offset must advance",
    "// Calculate Y позицию": "// Calculate Y position",
    "// Skip lines вне видимой области": "// Skip lines outside visible area",
    "// Current line highlight": "// Current line highlight",
    "// Selection": "// Selection",
    "// Search match highlight": "// Search match highlight",
    "// Check if match попадает в текущую строку": "// Check if match falls in current line",
    "// Current match - ярче": "// Current match - brighter",
    "// Line number": "// Line number",
    "// Line text с подсветкой синтаксиса (с кэшированием)": "// Line text with syntax highlighting (with caching)",
    "// Check cache": "// Check cache",
    "// Use cache": "// Use cache",
    "// Tokenize и cache": "// Tokenize and cache",
    "// Save в cache": "// Save to cache",
    "// Состояние ДО строки": "// State BEFORE line",
    "// Try highlighting via WASM plugin": "// Try highlighting via WASM plugin",
    "// Check cache для плагина": "// Check cache for plugin",
    "// Tokenize через плагин": "// Tokenize via plugin",
    "// Bracket matching highlight (для Zig файлов)": "// Bracket matching highlight (for Zig files)",
    "// Check скобку под курсором или перед ним": "// Check bracket under or before cursor",
    "// Find позиции для подсветки": "// Find positions to highlight",
    "// Highlight if на текущей строке": "// Highlight if on current line",
    "// Cursor (только если редактор в фокусе)": "// Cursor (only if editor is focused)",
    "// Move к следующей строке": "// Move to next line",
    "// For scrollbars use cached value": "// For scrollbars use cached value",
    "// Disable scissor после рендеринга контента редактора": "// Disable scissor after rendering editor content",
    "// === Scrollbars (внутри editor) ===": "// === Scrollbars (inside editor) ===",
    "// Horizontal scrollbar (внизу editor блока)": "// Horizontal scrollbar (bottom of editor block)",
    "// Check hover": "// Check hover",
    "// Background (подсвечивается при hover)": "// Background (highlights on hover)",
    "// Thumb (размер пропорционален видимой области)": "// Thumb (size proportional to visible area)",
    "// Thumb highlight при hover": "// Thumb highlight on hover",
    "// Vertical scrollbar (справа внутри editor)": "// Vertical scrollbar (right inside editor)",
    "// Background": "// Background",
    "// Thumb": "// Thumb",
    "// === Sidebar (rounded block с мягкой тенью) ===": "// === Sidebar (rounded block with soft shadow) ===",
    "// Soft shadow для sidebar": "// Soft shadow for sidebar",
    "// Main block - тёмно-серый с лёгким персиковым оттенком": "// Main block - dark gray with light peach tint",
    "// === Resize bar (правый край sidebar) - маленькая ручка по центру ===": "// === Resize bar (right edge of sidebar) - small handle in center ===",
    "// Handle рисуется в конце sidebar блока": "// Handle drawn at end of sidebar block",
    "// === Sidebar Tabs (с SVG иконками) ===": "// === Sidebar Tabs (with SVG icons) ===",
    "// Square tabs для иконок": "// Square tabs for icons",
    "// Tab background + glow при hover": "// Tab background + glow on hover",
    "// SVG icon": "// SVG icon",
    "// Separator под табами": "// Separator under tabs",
    "// Header - название активной вкладки": "// Header - active tab name",
    "// Empty Explorer state с кнопкой Open Folder": "// Empty Explorer state with Open Folder button",
    "// Glow + button background": "// Glow + button background",
    "// Button frame (при hover) - полная рамка": "// Button frame (on hover) - full frame",
    "// Top line": "// Top line",
    "// Bottom line": "// Bottom line",
    "// Left line": "// Left line",
    "// Right line": "// Right line",
    "// Corners (маленькие квадратики для скругления)": "// Corners (small squares for rounding)",
    "// Folder icon (SVG)": "// Folder icon (SVG)",
    "// Button text": "// Button text",
    "// Hint below": "// Hint below",
    "// Area для списка файлов (учитываем высоту табов + header)": "// Area for file list (account for tabs + header height)",
    "// Calculate total content height": "// Calculate total content height",
    "// Draw files": "// Draw files",
    "// Element background (красивый блок)": "// Element background (nice block)",
    "// Dark peach для выделенного": "// Dark peach for selected",
    "// Glow + background для hover": "// Glow + background for hover",
    "// Expansion icon для папок": "// Expansion icon for folders",
    "// Triangle indicator (поворачивается при анимации)": "// Triangle indicator (rotates during animation)",
    "// Expanded - стрелка вниз": "// Expanded - arrow down",
    "// Collapsed - стрелка вправо": "// Collapsed - arrow right",
    "// Folder name (или поле ввода при переименовании)": "// Folder name (or input field when renaming)",
    "// Regular file с SVG иконкой по расширению": "// Regular file with SVG icon by extension",
    "// Draw SVG icon (16x16)": "// Draw SVG icon (16x16)",
    "// File name после иконки (normal display)": "// File name after icon (normal display)",
    "// Explorer scrollbar (если нужен)": "// Explorer scrollbar (if needed)",
    "// Scrollbar background": "// Scrollbar background",
    "// \"Installed\" header": "// \"Installed\" header",
    "// Get загруженные плагины": "// Get loaded plugins",
    "// Empty list": "// Empty list",
    "// List загруженных плагинов": "// List of loaded plugins",
    "// Plugin background (светлее при hover) + glow": "// Plugin background (lighter on hover) + glow",
    "// Icon (определяем по расширениям)": "// Icon (determined by extensions)",
    "// Plugin name": "// Plugin name",
    "// Separator и путь к папке плагинов": "// Separator and path to plugins folder",
    "// Resize handle - маленькая ручка по центру, меняет цвет при hover": "// Resize handle - small handle in center, changes color on hover",
    "// === Tab Bar (внизу окна, с мягкой тенью) ===": "// === Tab Bar (bottom of window, with soft shadow) ===",
    "// Tab bar starts сразу после editor block с отступом 10px": "// Tab bar starts right after editor block with 10px margin",
    "// Soft shadow для tab bar": "// Soft shadow for tab bar",
    "// Tab bar background": "// Tab bar background",
    "// Draw tabs": "// Draw tabs",
    "// Tab width: иконка + имя + отступы + кнопка закрытия": "// Tab width: icon + name + padding + close button",
    "// Enlarged tabs": "// Enlarged tabs",
    "// Optimization: skip tabs за пределами видимой области": "// Optimization: skip tabs outside visible area",
    "// All subsequent tabs тоже невидимы": "// All subsequent tabs are also invisible",
    "// Get SVG file icon для вкладки": "// Get SVG file icon for tab",
    "// Tab background - только при active или hover + glow": "// Tab background - only on active or hover + glow",
    "// Unsaved changes indicator (кружок)": "// Unsaved changes indicator (circle)",
    "// SVG file icon (20x20)": "// SVG file icon (20x20)",
    "// Tab name (белый текст) - центрирование по вертикали": "// Tab name (white text) - vertical centering",
    "// Close button (×) + glow при hover": "// Close button (x) + glow on hover",
    "// Separator между вкладками": "// Separator between tabs",
    "// \"+\" button для новой вкладки - квадратная, центрированная": "// \"+\" button for new tab - square, centered",
    "// Greenish при hover": "// Greenish on hover",
    "// Green при hover": "// Green on hover",
    "// Panel background": "// Panel background",
    "// Resize handle (горизонтальная полоска сверху)": "// Resize handle (horizontal bar on top)",
    "// Close button с hover эффектом + glow": "// Close button with hover effect + glow",
    "// Separator": "// Separator",
    "// Panel content": "// Panel content",
    "// Line color по типу": "// Line color by type",
    "// warning - yellow": "// warning - yellow",
    "// error - red": "// error - red",
    "// === Search bar (поверх редактора) ===": "// === Search bar (on top of editor) ===",
    "// Shadow": "// Shadow",
    "// Search icon": "// Search icon",
    "// Input field (background)": "// Input field (background)",
    "// Query text": "// Query text",
    "// Cursor в поле ввода (мигающий эффект можно добавить позже)": "// Cursor in input field (blinking effect can be added later)",
    "// Match counter": "// Match counter",
    "// Navigation buttons (< и >)": "// Navigation buttons (< and >)",
    "// === Dropdown menus (поверх sidebar) ===": "// === Dropdown menus (on top of sidebar) ===",
    "// Dropdown position": "// Dropdown position",
    "// Common menu sizes": "// Common menu sizes",
    "// Items для каждого меню": "// Items for each menu",
    "// Soft shadow": "// Soft shadow",
    "// === Settings popup (rounded с мягкой тенью) ===": "// === Settings popup (rounded with soft shadow) ===",
    "// Popup background": "// Popup background",
    "// Close button (rounded, с hover + glow)": "// Close button (rounded, with hover + glow)",
    "// Checkbox border (внешний) - ярче при hover": "// Checkbox border (outer) - brighter on hover",
    "// Checkbox background (inner)": "// Checkbox background (inner)",
    "// Label - ярче при hover": "// Label - brighter on hover",
    "// Render slider": "// Render slider",
    "// Track background": "// Track background",
    "// Filled part": "// Filled part",
    "// Update slider position для обработки событий": "// Update slider position for event handling",
    "// Get scaled sizes": "// Get scaled sizes",
    "// Not used напрямую for now": "// Not used directly for now",
    "// Titlebar background (rounded сверху)": "// Titlebar background (rounded on top)",
    "// Overlap bottom part чтобы убрать скругление снизу": "// Overlap bottom part to remove bottom rounding",
    "// === Menu block слева - unified block как window controls ===": "// === Menu block left - unified block like window controls ===",
    "// Menu block background (rounded)": "// Menu block background (rounded)",
    "// File section (левая - rounded слева)": "// File section (left - rounded on left)",
    "// Edit section (центр - без закруглений)": "// Edit section (center - no rounding)",
    "// View section (правая - rounded справа)": "// View section (right - rounded on right)",
    "// Separators между секциями меню": "// Separators between menu sections",
    "// === Window controls - unified button справа с 3 секциями ===": "// === Window controls - unified button on right with 3 sections ===",
    "// Button background (rounded)": "// Button background (rounded)",
    "// Determine какая секция под курсором": "// Determine which section is under cursor",
    "// Section 0: Minimize (слева)": "// Section 0: Minimize (left)",
    "// Section 1: Maximize/Restore (центр)": "// Section 1: Maximize/Restore (center)",
    "// Section 2: Close (справа)": "// Section 2: Close (right)",
    "// Separators между секциями": "// Separators between sections",
    "// Use zenity для выбора папки": "// Use zenity to select folder",
    "// Remove trailing newline": "// Remove trailing newline",
    "// Reset all states": "// Reset all states",
    "// Skip hidden files": "// Skip hidden files",
    "// Build full path": "// Build full path",
    "// Sort: папки сначала, потом by name": "// Sort: folders first, then by name",
    "// Simple bubble sort (папки сначала, потом alphabetically)": "// Simple bubble sort (folders first, then alphabetically)",
    "// Folders go first": "// Folders go first",
    "// Same type - compare by name": "// Same type - compare by name",
    "// Open directory": "// Open directory",
    "// Collect child elements во временный буфер": "// Collect child elements into temp buffer",
    "// Full path": "// Full path",
    "// Sort temp buffer (папки сначала, потом alphabetically)": "// Sort temp buffer (folders first, then alphabetically)",
    "// Insert после idx": "// Insert after idx",
    "// Check что есть место": "// Check that there's space",
    "// Shift existing elements вправо": "// Shift existing elements right",
    "// Update parent ссылки": "// Update parent references",
    "// Insert new elements": "// Insert new elements",
    "// Find все дочерние элементы (прямые и вложенные)": "// Find all child elements (direct and nested)",
    "// Count сколько элементов нужно удалить": "// Count how many elements to delete",
    "// Check, является ли элемент потомком idx": "// Check if element is descendant of idx",
    "// Children идут подряд, так что можно выйти": "// Children are contiguous, so we can exit",
    "// Delete дочерние элементы, shifting remaining влево": "// Delete child elements, shifting remaining left",
    "// Write buffer contents": "// Write buffer contents",
    "// Check, не открыт ли уже этот файл": "// Check if this file is already open",
    "// File уже открыт - switch to it": "// File already open - switch to it",
    "// Save scroll текущей вкладки": "// Save scroll of current tab",
    "// Extract file name из пути": "// Extract file name from path",
    "// Load file": "// Load file",
    "// уровень вложенности": "// nesting level",
    # Add more any remaining Russian words
    "Максимум": "Maximum",
    "Минимум": "Minimum",
    "множитель": "multiplier",
    "символов/сек": "chars/sec",
    "строк/сек": "lines/sec",
}

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for rus, eng in additional_translations.items():
        if rus in content:
            content = content.replace(rus, eng)
            count += 1

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Translated {count} patterns")

    # Count remaining Russian comments
    import subprocess
    result = subprocess.run(['grep', '-c', '//.*[а-яА-ЯёЁ]', filepath], capture_output=True, text=True)
    print(f"Remaining Russian comments: {result.stdout.strip()}")

if __name__ == "__main__":
    translate_file("/home/artemjs/Moon-code/src/main.zig")
